# Generated by Django 4.0.4 on 2022-05-05 10:17

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='note',
            new_name='note1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='note2',
            field=wagtail.core.fields.RichTextField(default='def'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='note3',
            field=wagtail.core.fields.RichTextField(default='def'),
            preserve_default=False,
        ),
    ]
