# Generated by Django 4.0.4 on 2022-05-05 17:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_note1_remove_homepage_note2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='extra_info',
            field=wagtail.core.fields.RichTextField(default='def'),
            preserve_default=False,
        ),
    ]
