# Generated by Django 3.2.12 on 2022-04-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ImageField(default='imgs/1.png', upload_to='imgs/'),
        ),
    ]
